echo "We are trying this practical from linux EC2"
echo "We are from batch-33 and learning git/gihub"
echo "We are learning Branching"
echo "Git fork and git clone"
echo "lets learn devops"
echo "want to study more"
echo " let's learn together"
echo " join Devops classes"
echo " i am checking commit"